### ISSUE TITLE
After Setup everything redirects to port 80

### ISSUE THREAD

**Issue by productivepod** [daltonplan/daltonplan#3]
I have completed a setup on subdomain of my shared hosting. 
my URL is : https://dalton.[mysite].com
and this pointing to folder public of the installation . 

But when I see login page or any resources keep loading and redirecting to  https://dalton.[mysite].com:80/login

**Comment by TheLavaBlock** [comment]
Thanks for your feedback. Did you also run the `/setup` and get the owner login? Then you should be able to get in with it. 

Unfortunately I currently do not get to work on the project further. In the past I have also set up subdomains.

Please explain again what exactly you have done and how the problem occurs in order to avoid misunderstandings.

**Comment by productivepod** [comment]
To make this work for now - I have removed the line which was calculating a port. there it found as port 80 because it is true for my server but actually it is running without any port in URLs . So may be it should be picked only from configs manually mentioned. Not calculated,

**Comment by TheLavaBlock** [comment]
Thanks for your feedback and your workaround. As soon as others come with the same problem, we should adjust the code. I'll close this for now.
